// <auto-generated />
namespace PTPMQL3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Alter_Column_Student_Address_Age : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Column_Student_Address_Age));
        
        string IMigrationMetadata.Id
        {
            get { return "202103081550368_Alter_Column_Student_Address_Age"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
